baseURL = "https://urgenth.cc"
title = "Urgenth"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"
#googleAnalytics = "G-XXXXXXXXXX"

[params]
fancyTitle = "Urgenth" # title for frontpage, may include image
copyright = "Urgenth"
description = 'The first logistics blockchain'
startbuttonText = "Soon"
startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#custom_sass = "bar.scss"
images = ["/images/favicon.ico"]



[[params.menu.main]]
url = '/'
title = "Home"

#[[params.menu.main]]
#url = '/posts/'
#title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"



[params.social]
twitter = "urgentchain"
#mastodon = "email"
#github = ""
#facebook = ""
#youtube = ""
#instagram = ""
#dribble = ""
email = "support@urgenth.cc"
# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"


